[package]
name = "mathfun"
version = "0.1.1"
edition = "2021"
authors = ["mert-kurttutan"]
description = "high-performance math functions"
readme = "./README.md"
license = "MIT"
keywords = ["high-performance", "math"]
repository = "https://github.com/mert-kurttutan/mathfun-rs"
rust-version = "1.65"

[dependencies]
once_cell = "1.20.2"
raw-cpuid = "11.3.0"


[dev-dependencies]
# disable rayon to enable testing on wasm32 target
criterion = {version="0.5", features=["plotters", "cargo_bench_support"], default-features=false}
rand = "0.9"
libloading = "0.8.5"
libc = "0.2"

[features]
default = ["std"]
std = []

[[bench]]
name = "bench"
harness = false